# Core Colors
background            #111318
foreground            #e2e2e9
selection_foreground  #aec6ff
selection_background  #112f60
cursor                #aec6ff
cursor_text_color     #111318

# Regular Colors
color0  #111318
color1  #ffb4ab
color2  #aec6ff
color3  #debcdf
color4  #d8e2ff
color5  #dbe2f9
color6  #bfc6dc
color7  #e2e2e9

# Bright Colors
color8  #37393e
color9  #ffb4ab
color10 #aec6ff
color11 #debcdf
color12 #d8e2ff
color13 #dbe2f9 
color14 #bfc6dc
color15 #e2e2e9
