# Core Colors
background            #0f1512
foreground            #dee4de
selection_foreground  #8cd5b4
selection_background  #003826
cursor                #8cd5b4
cursor_text_color     #0f1512

# Regular Colors
color0  #0f1512
color1  #ffb4ab
color2  #8cd5b4
color3  #a6ccdf
color4  #a8f2cf
color5  #cfe9da
color6  #b3ccbe
color7  #dee4de

# Bright Colors
color8  #353b37
color9  #ffb4ab
color10 #8cd5b4
color11 #a6ccdf
color12 #a8f2cf
color13 #cfe9da 
color14 #b3ccbe
color15 #dee4de
