# Core Colors
background            #16130b
foreground            #e9e2d4
selection_foreground  #ddc66e
selection_background  #3a3000
cursor                #ddc66e
cursor_text_color     #16130b

# Regular Colors
color0  #16130b
color1  #ffb4ab
color2  #ddc66e
color3  #aad0b2
color4  #fae287
color5  #efe2bc
color6  #d2c6a1
color7  #e9e2d4

# Bright Colors
color8  #3c392f
color9  #ffb4ab
color10 #ddc66e
color11 #aad0b2
color12 #fae287
color13 #efe2bc 
color14 #d2c6a1
color15 #e9e2d4
