$primaryMonitor   = HDMI-A-1
$secondaryMonitor = DP-2

monitor = $primaryMonitor, 2560x1440, 0x0, 1
monitor = $secondaryMonitor, 2560x1440, 2560x0, 1

workspace = 1, monitor:$primaryMonitor
workspace = 2, monitor:$primaryMonitor
workspace = 3, monitor:$primaryMonitor
workspace = 4, monitor:$secondaryMonitor
workspace = 5, monitor:$secondaryMonitor
workspace = 6, monitor:$secondaryMonitor

windowrule = workspace 1, match:class ^(firefox)$
windowrule = workspace 2, match:class ^(Alacritty)$
windowrule = workspace 3, match:class ^(Steam)$
windowrule = workspace 4, match:class ^(discord)$
windowrule = workspace 4, match:class ^(Spotify)$
