$primaryMonitor   = HDMI-A-1
$secondaryMonitor = DP-2

monitor = $primaryMonitor, 3840x2160, 0x0, 1.5
monitor = $secondaryMonitor, 2560x1440, 2560x0, 1

workspace = 1, monitor:$primaryMonitor
workspace = 2, monitor:$primaryMonitor
workspace = 3, monitor:$primaryMonitor
workspace = 4, monitor:$secondaryMonitor
workspace = 5, monitor:$secondaryMonitor
workspace = 6, monitor:$secondaryMonitor
workspace = 7, monitor:$secondaryMonitor
workspace = 8, monitor:$secondaryMonitor
workspace = 9, monitor:$secondaryMonitor

windowrule = workspace 1, class:^(firefox)$
windowrule = workspace 2, class:^(Alacritty)$
windowrule = workspace 3, class:^(Steam)$
windowrule = workspace 4, class:^(discord)$
windowrule = workspace 4, class:^(Spotify)$
