# multimedia
windowrule = tag +multimedia_video, class:mpv
windowrule = tag +multimedia_video, class:Mpv
windowrule = tag +multimedia_video, class:vlc

# settings
windowrule = tag +settings, class:nm-applet
windowrule = tag +settings, class:nm-connection-editor
windowrule = tag +settings, class:blueman-manager
windowrule = tag +settings, class:org.gnome.FileRoller
windowrule = tag +settings, class:org.gnome.DiskUtility
windowrule = tag +settings, class:wihotspot
windowrule = tag +settings, class:wihotspot-gui

# viewer
windowrule = tag +viewer, class:org.gnome.SystemMonitor
windowrule = tag +viewer, class:org.gnome.Evince
windowrule = tag +viewer, class:eog
windowrule = tag +viewer, class:org.gnome.Loupe
