# multimedia
windowrule = tag +multimedia_video, match:class mpv
windowrule = tag +multimedia_video, match:class Mpv
windowrule = tag +multimedia_video, match:class vlc

# settings
windowrule = tag +settings, match:class nm-applet
windowrule = tag +settings, match:class nm-connection-editor
windowrule = tag +settings, match:class blueman-manager
windowrule = tag +settings, match:class org.gnome.FileRoller
windowrule = tag +settings, match:class org.gnome.DiskUtility
windowrule = tag +settings, match:class wihotspot
windowrule = tag +settings, match:class wihotspot-gui

# viewer
windowrule = tag +viewer, match:class org.gnome.SystemMonitor
windowrule = tag +viewer, match:class org.gnome.Evince
windowrule = tag +viewer, match:class eog
windowrule = tag +viewer, match:class org.gnome.Loupe
