# LAYER RULES
layerrule = animation popin 80%, rofi
layerrule = animation popin 80%, logout_dialog
layerrule = animation popin 80%, swaync-control-center
layerrule = animation popin 80%, swaync-notification-window

#FLOAT
windowrule = float, tag:settings*
windowrule = float, tag:viewer*
windowrule = float, tag:multimedia_video*
windowrule = size 900 506, tag:multimedia_video*
windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = size 50% 60%, class:org.pulseaudio.pavucontrol

# Ignore maximize requests from apps
windowrule = suppressevent maximize fullscreen, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# POP UPS AND DIALOGUES
windowrule = float, title:Save As
windowrule = float, title:Save a File
windowrule = float, title:Pick Files
windowrule = size 50% 60%, title:Save As
windowrule = size 50% 60%, title:Save a File
windowrule = size 50% 60%, title:Pick Files
windowrule = center, title:Save As
windowrule = center, title:Save a File
windowrule = center, title:Pick Files

windowrule = float, initial_title:Open Files
windowrule = size 70% 60%, initial_title:Open Files
