# APPLIACTIONS OPACITY
windowrule = opacity 1.0, match:tag multimedia_video*
windowrule = opacity 0.8, match:tag settings*
windowrule = opacity 0.8, match:class org.gnome.Nautilus
windowrule = opacity 0.9, match:class gedit
windowrule = opacity 0.9, match:class org.gnome.TextEditor
windowrule = opacity 0.9, match:class mousepad
windowrule = opacity 0.9, match:class org.pulseaudio.pavucontrol
windowrule = opacity 0.9, match:class Alacritty
windowrule = opacity 0.85 override 0.7 override 1 override, match:class discord
windowrule = opacity 0.85 override 0.7 override 1 override, match:class vesktop
windowrule = opacity 0.85 override 0.7 override 1 override, match:class org.telegram.desktop
windowrule = opacity 0.8 override 0.6 override 1 override, match:class Spotify
windowrule = opacity 0.9 override 0.7 override 1 override, match:class zen
#windowrule = opacity 0.8 override 0.6 override 1 override, match:tag viewer*

# LAYER RULES
#layerrule = blur on, match:namespace rofi
#layerrule = ignore_alpha 0.5, match:namespace rofi
#layerrule = dim_around on, match:namespace rofi
#layerrule = animation popin 10%, match:namespace rofi
#layerrule = blur on, match:namespace notifications
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = blur on, match:namespace logout_dialog

# SWAYNC BLUR & XRAY
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = xray off, match:namespace swaync-control-center
layerrule = xray off, match:namespace swaync-notification-window

#FLOAT
windowrule = float on, match:tag settings*
windowrule = float on, match:tag viewer*
windowrule = float on, match:tag multimedia_video*
windowrule = size 900 506, match:tag multimedia_video*
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = size 50% 60%, match:class org.pulseaudio.pavucontrol

# Ignore maximize requests from apps
windowrule = suppress_event maximize fullscreen, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# POP UPS AND DIALOGUES
windowrule = float on, match:title Save As
windowrule = float on, match:title Save a File
windowrule = float on, match:title Pick Files
windowrule = size 50% 60%, match:title Save As
windowrule = size 50% 60%, match:title Save a File
windowrule = size 50% 60%, match:title Pick Files
windowrule = center on, match:title Save As
windowrule = center on, match:title Save a File
windowrule = center on, match:title Pick Files

windowrule = float on, match:initial_title Open Files
windowrule = size 70% 60%, match:initial_title Open Files
