# LAYER RULES
layerrule = animation popin 80%, match:namespace rofi
layerrule = animation popin 80%, match:namespace logout_dialog
layerrule = animation popin 80%, match:namespace swaync-control-center
layerrule = animation popin 80%, match:namespace swaync-notification-window

#FLOAT
windowrule = float on, match:tag settings*
windowrule = float on, match:tag viewer*
windowrule = float on, match:tag multimedia_video*
windowrule = size 900 506, match:tag multimedia_video*
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = size 50% 60%, match:class org.pulseaudio.pavucontrol

# Ignore maximize requests from apps
windowrule = suppress_event maximize fullscreen, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# POP UPS AND DIALOGUES
windowrule = float on, match:title Save As
windowrule = float on, match:title Save a File
windowrule = float on, match:title Pick Files
windowrule = size 50% 60%, match:title Save As
windowrule = size 50% 60%, match:title Save a File
windowrule = size 50% 60%, match:title Pick Files
windowrule = center on, match:title Save As
windowrule = center on, match:title Save a File
windowrule = center on, match:title Pick Files

windowrule = float on, match:initial_title Open Files
windowrule = size 70% 60%, match:initial_title Open Files
