version: "3"

vars:
  BINARY: dots

tasks:
  default:
    cmds:
      - task: install

  install:
    desc: Setup dotfiles
    cmds:
      - go build -o {{.BINARY}} .
      - ./{{.BINARY}} install {{.CLI_ARGS}}

  uninstall:
    desc: Remove symlinks
    cmds:
      - go build -o {{.BINARY}} .
      - ./{{.BINARY}} uninstall {{.CLI_ARGS}}

  benchmark:
    desc: Test shell startup time
    cmds:
      - go build -o {{.BINARY}} .
      - ./{{.BINARY}} benchmark
