# One Dark (darker) palette
%hidden TH_BG="#1f2329"
%hidden TH_FG="#a0a8b7"
%hidden TH_BLACK="#0e1013"
%hidden TH_GUTTER="#30363f"
%hidden TH_COMMENT="#535965"
%hidden TH_RED="#e55561"
%hidden TH_GREEN="#8ebd6b"
%hidden TH_YELLOW="#cc9057"
%hidden TH_BLUE="#4fa6ed"
%hidden TH_MAGENTA="#bf68d9"
%hidden TH_CYAN="#48b0bd"
