# Default terminal palette
%hidden TH_BG="#1c1c1c"
%hidden TH_FG="#c0c0c0"
%hidden TH_BLACK="#000000"
%hidden TH_GUTTER="#3a3a3a"
%hidden TH_COMMENT="#555753"
%hidden TH_RED="#cc0000"
%hidden TH_GREEN="#4e9a06"
%hidden TH_YELLOW="#c4a000"
%hidden TH_BLUE="#3465a4"
%hidden TH_MAGENTA="#75507b"
%hidden TH_CYAN="#06989a"
