# Gruvbox Dark palette
%hidden TH_BG="#282828"
%hidden TH_FG="#ebdbb2"
%hidden TH_BLACK="#1d2021"
%hidden TH_GUTTER="#3c3836"
%hidden TH_COMMENT="#928374"
%hidden TH_RED="#fb4934"
%hidden TH_GREEN="#b8bb26"
%hidden TH_YELLOW="#fabd2f"
%hidden TH_BLUE="#83a598"
%hidden TH_MAGENTA="#d3869b"
%hidden TH_CYAN="#8ec07c"
